#!/bin/bash
# S3 Deployment Script
# Deploys drawing app frontend to AWS S3

set -e

BUCKET_NAME="drawing-app-frontend"
REGION="us-east-1"
ENVIRONMENT="${ENVIRONMENT:-dev}"
DEPLOY_TABLE="DeploymentStats-${ENVIRONMENT}"
API_BASE="${API_BASE:-${BACKEND_URL:-}}"
WS_BASE="${WS_BASE:-${API_BASE:-${BACKEND_WS_URL:-}}}"
CONFIG_PATH="public/config.js"
RUN_ALL=false
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

for arg in "$@"; do
  case "$arg" in
    -all|--all) RUN_ALL=true ;;
    -h|--help)
      echo "Usage: $0 [-all]"
      echo "  -all   Deploy backend (deploy-lambda.sh) then frontend (this script)"
      exit 0
      ;;
  esac
done

if $RUN_ALL; then
  echo "=========================================="
  echo "Running backend deploy (deploy-lambda.sh)"
  echo "=========================================="
  "${SCRIPT_DIR}/deploy-lambda.sh"
  echo ""
  echo "Backend deploy finished. Continuing with frontend deploy..."
  echo ""
fi

echo "=========================================="
echo "Deploying Frontend to S3"
echo "=========================================="
echo "Bucket: $BUCKET_NAME"
echo "Region: $REGION"
echo "Environment: $ENVIRONMENT"
echo "API base: ${API_BASE:-<same-origin>}"
echo "WS base: ${WS_BASE:-<same-origin>}"
echo ""

# Optionally write runtime config so the static site knows where the backend lives.
# If API_BASE/WS_BASE are not provided, keep any existing config.js untouched.
if [ -n "$API_BASE" ] || [ -n "$WS_BASE" ]; then
  cat > "$CONFIG_PATH" <<EOF
// Auto-generated by deploy.sh
window.__CONFIG = {
  API_BASE: "${API_BASE}",
  WS_BASE: "${WS_BASE}"
};
window.__API_BASE = window.__CONFIG.API_BASE;
window.__WS_BASE = window.__CONFIG.WS_BASE;
EOF
  echo "Wrote runtime config to ${CONFIG_PATH}"
else
  if [ -f "$CONFIG_PATH" ]; then
    echo "API_BASE/WS_BASE not provided; leaving existing ${CONFIG_PATH} unchanged."
  else
    echo "API_BASE/WS_BASE not provided and ${CONFIG_PATH} not found. Create it manually or rerun with values to generate."
  fi
fi

# Create bucket if doesn't exist
if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
    aws s3 mb "s3://$BUCKET_NAME" --region "$REGION"
fi

# Enable website hosting
aws s3 website "s3://$BUCKET_NAME" --index-document index.html

# Disable block public access
aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
    "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

# Set public read policy
cat > /tmp/policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": "*",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
  }]
}
EOF

aws s3api put-bucket-policy --bucket "$BUCKET_NAME" --policy file:///tmp/policy.json
rm /tmp/policy.json

# Upload files
aws s3 sync public/ "s3://$BUCKET_NAME/" --delete

echo ""
echo "=========================================="
echo "✓ Frontend deployed successfully!"
echo "=========================================="
echo "Frontend URL: http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com"

# Increment deploy counter in DynamoDB
echo "Updating deploy counter in DynamoDB table ${DEPLOY_TABLE}..."
aws dynamodb update-item \
  --table-name "$DEPLOY_TABLE" \
  --key '{"id": {"S": "deploy"}}' \
  --update-expression "ADD deployCount :inc" \
  --expression-attribute-values '{":inc": {"N": "1"}}' \
  --region "$REGION" || echo "Warning: failed to update deploy counter"

echo "Done."
