#!/bin/bash
# S3 Deployment Script
# Deploys drawing app frontend to AWS S3

set -e

BUCKET_NAME="drawing-app-frontend"
REGION="us-east-1"
ENVIRONMENT="${ENVIRONMENT:-dev}"
DEPLOY_TABLE="DeploymentStats-${ENVIRONMENT}"
API_BASE="${API_BASE:-${BACKEND_URL:-}}"
WS_BASE="${WS_BASE:-${API_BASE:-${BACKEND_WS_URL:-}}}"
CONFIG_PATH="public/config.js"
RUN_ALL=false
RUN_HARD=false
VERBOSE=false
RESET_TABLES=false
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

for arg in "$@"; do
  case "$arg" in
    -all|--all) RUN_ALL=true ;;
    -hard|--hard) RUN_HARD=true ;;
    -reset|--reset) RESET_TABLES=true ;;
    -v|--verbose) VERBOSE=true ;;
    -h|--help)
      echo "Usage: $0 [-all] [-hard] [-reset] [-v]"
      echo "  -all    Deploy backend (deploy-lambda.sh) then frontend (this script)"
      echo "  -hard   When combined with -all, recreate prereqs (DynamoDB tables) before backend deploy"
      echo "  -reset  When combined with -all, wipe Rooms/CanvasObjects tables before setup (destructive)"
      echo "  -v      Verbose output (table checks, setup logs)"
      exit 0
      ;;
  esac
done

ensure_tables() {
  local env="$1"
  local region="${AWS_REGION:-us-east-1}"
  local missing=()
  local tables=("Rooms-${env}" "CanvasObjects-${env}" "Connections-${env}" "DeploymentStats-${env}")

  for t in "${tables[@]}"; do
    if ! aws dynamodb describe-table --table-name "$t" --region "$region" >/dev/null 2>&1; then
      missing+=("$t")
    fi
  done

  if [ "$RESET_TABLES" = true ]; then
    echo "Resetting Rooms/CanvasObjects tables for ${env}..."
    # Confirm destructive reset
    read -r -p "This will wipe Rooms-${env} and CanvasObjects-${env}. Proceed? (y/N): " yn
    case "$yn" in
      [Yy]* ) ;;
      * ) echo "Abort reset."; exit 1 ;;
    esac
    read -r -s -p "Enter password phrase: " pw; echo ""
    exp_hash=$(printf 'yes, I%s sure' \" | shasum -a 256 2>/dev/null | awk '{print $1}')
    # If shasum unavailable, try sha256sum
    if [ -z "$exp_hash" ]; then
      exp_hash=$(printf 'yes, I%s sure' \" | sha256sum 2>/dev/null | awk '{print $1}')
    fi
    inp_hash=$(printf '%s' "$pw" | shasum -a 256 2>/dev/null | awk '{print $1}')
    if [ -z "$inp_hash" ]; then
      inp_hash=$(printf '%s' "$pw" | sha256sum 2>/dev/null | awk '{print $1}')
    fi
    if [ -z "$exp_hash" ] || [ "$inp_hash" != "$exp_hash" ]; then
      echo "Invalid password phrase. Abort reset."
      exit 1
    fi
    for t in "Rooms-${env}" "CanvasObjects-${env}"; do
      aws dynamodb delete-table --table-name "$t" --region "$region" >/dev/null 2>&1 || true
      aws dynamodb wait table-not-exists --table-name "$t" --region "$region" >/dev/null 2>&1 || true
    done
  fi

  if [ "${#missing[@]}" -gt 0 ] || [ "$RUN_HARD" = true ] || [ "$RESET_TABLES" = true ]; then
    echo "Preparing DynamoDB tables (${env})..."
    if [ "$VERBOSE" = true ]; then
      (cd "${SCRIPT_DIR}/backend/infrastructure" && ENVIRONMENT="$env" VERBOSE=1 ./setup-dynamodb.sh)
    else
      (cd "${SCRIPT_DIR}/backend/infrastructure" && ENVIRONMENT="$env" VERBOSE=0 ./setup-dynamodb.sh)
    fi
  else
    echo "DynamoDB tables present for ${env}; skipping setup."
  fi
}

if $RUN_ALL; then
  echo "=========================================="
  echo "Running backend deploy (deploy-lambda.sh)"
  echo "=========================================="
  ensure_tables "${ENVIRONMENT}"
  LAMBDA_ARGS=()
  if [ "$VERBOSE" = true ]; then
    LAMBDA_ARGS+=("-v")
  fi
  "${SCRIPT_DIR}/deploy-lambda.sh" "${LAMBDA_ARGS[@]}"
  echo ""
  echo "Backend deploy finished. Continuing with frontend deploy..."
  echo ""
fi

echo "=========================================="
echo "Deploying Frontend to S3"
echo "=========================================="
echo "Bucket: $BUCKET_NAME"
echo "Region: $REGION"
echo "Environment: $ENVIRONMENT"
echo "API base: ${API_BASE:-<same-origin>}"
echo "WS base: ${WS_BASE:-<same-origin>}"
echo ""

# Optionally write runtime config so the static site knows where the backend lives.
# If API_BASE/WS_BASE are not provided, keep any existing config.js untouched.
if [ -n "$API_BASE" ] || [ -n "$WS_BASE" ]; then
  cat > "$CONFIG_PATH" <<EOF
// Auto-generated by deploy.sh
window.__CONFIG = {
  API_BASE: "${API_BASE}",
  WS_BASE: "${WS_BASE}"
};
window.__API_BASE = window.__CONFIG.API_BASE;
window.__WS_BASE = window.__CONFIG.WS_BASE;
EOF
  echo "Wrote runtime config to ${CONFIG_PATH}"
else
  if [ -f "$CONFIG_PATH" ]; then
    echo "API_BASE/WS_BASE not provided; leaving existing ${CONFIG_PATH} unchanged."
  else
    echo "API_BASE/WS_BASE not provided and ${CONFIG_PATH} not found. Create it manually or rerun with values to generate."
  fi
fi

# Create bucket if doesn't exist
if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
    aws s3 mb "s3://$BUCKET_NAME" --region "$REGION"
fi

# Enable website hosting
aws s3 website "s3://$BUCKET_NAME" --index-document index.html

# Disable block public access
aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
    "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

# Set public read policy
cat > /tmp/policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": "*",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
  }]
}
EOF

aws s3api put-bucket-policy --bucket "$BUCKET_NAME" --policy file:///tmp/policy.json
rm /tmp/policy.json

# Upload files
aws s3 sync public/ "s3://$BUCKET_NAME/" --delete

echo ""
echo "=========================================="
echo "✓ Frontend deployed successfully!"
echo "=========================================="
echo "Frontend URL: http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com"

# Increment deploy counter in DynamoDB
echo "Updating deploy counter in DynamoDB table ${DEPLOY_TABLE}..."
aws dynamodb update-item \
  --table-name "$DEPLOY_TABLE" \
  --key '{"id": {"S": "deploy"}}' \
  --update-expression "ADD deployCount :inc" \
  --expression-attribute-values '{":inc": {"N": "1"}}' \
  --region "$REGION" || echo "Warning: failed to update deploy counter"

echo "Done."
